### ISSUE TITLE
Integrate common floating point constants

### ISSUE THREAD

**Issue by b52** [rust-num/num#194] opened 2016-06-08 09:37 UTC
In most of my implementations involving generic floating point values I have the need to work with pi and/or e. Thus it would be really helpful to provide static functions to retrieve those values for the concrete type.

**Comment by cuviper** [comment] 2016-06-08 17:04
In general, `let e = Float::one().exp();` and  `let pi = (-Float::one()).acos();` should work.  We could provide these as default implementations and override the specific constants for `f32` and `f64`.

**Comment by cuviper** [comment] 2016-06-08 17:09
Associated constants would be nice too, rust-lang/rust#29646, but we couldn't provide defaults there.

**Comment by IvanUkhov** [comment] 2016-08-11 06:00
I agree that pretty much every mathematical constant can be computed using the methods that are already there. However, `(-Float::one()).acos()` and alike obscure the actual algorithm. Do we really want to see people in the Rust community writing this kind of generic code? Besides, who is willing to guarantee that `(-Float::one()).acos()` is indeed a zero-cost abstraction?

**Comment by cuviper** [comment] 2016-08-11 06:08
No, I don't expect people should do that -- it's just a way to write a generic default so it's not a breaking change.  We can provide the proper constants in the implementation for the concrete float types.

Care to write up a PR?

**Comment by IvanUkhov** [comment] 2016-08-11 06:20
@cuviper, first of all, I apologize if it sounded rude; no offense was intended. I’m an active user of `num` and really appreciate your work.

Yes, absolutely. If there are no objections, I’ll be happy to help.

**Comment by cuviper** [comment] 2016-08-11 06:41
No problem, sorry if I sounded too defensive. :)

**Comment by cuviper** [comment] 2016-08-16 01:36
Fixed by #220 -- thanks @IvanUkhov!

**Closed by cuviper** 2016-08-16 01:36 UTC
